### ISSUE TITLE
Not working for ACM Digital Library (dl.acm.org) links

### ISSUE THREAD

**Issue by gabrieleara** [RoiArthurB/Side-Auto_Sci-Hub#2]
I don't really know whether to post this issue here or on whereisscihub project, since it is used to get redirected to the actual sci-hub page, but I'll explain briefly.

Since ACM DL website uses a GET parameter to identify articles on their website (example: https://dl.acm.org/citation.cfm?id=2803202 ), where using whereisscihub to be redirected on the current sci-hub location the GET parameter doesn't get forwarded to the actual sci-hub webpage.

**Steps to reproduce the issue**

1. Open any paper page hosted on ACM DL website (you can take the link in the example above)
2. Use the extension button
3. Get redirected to whereisscihub website (in the previous example it took me to https://whereisscihub.now.sh/go/https://dl.acm.org/citation.cfm?id=2803202 )
4. Get redirected automatically to https://sci-hub.se/https://dl.acm.org/dl.cfm , regardless the paper you requested (sci-hub base url may be different depending on which version is used by whereisscihub).

PS: I am currently using Firefox as browser. Don't know if this issue applies to other browsers.

**Comment by RoiArthurB** [comment]
Ok I founded where the bug comes from :

So you where right, whereisscihub doesn't follow get parameter but sci-hub doesn't handle any parameter neither, it just takes the raw url name (whatever is the url composed of) and have a reference between that line and the PDF file.

So a simple workaround is to use the URL encodage (list [here](https://www.degraeve.com/reference/urlencoding.php) ) for the question mark character.

So your example url was this : 
https://dl.acm.org/citation.cfm?id=2803202 

and become that : 
https://dl.acm.org/citation.cfm%3Fid=2803202 

And if you use it within the whereisscihub redirection it will works perfectly ^^ 
https://whereisscihub.now.sh/go/https://dl.acm.org/citation.cfm%3Fid=2803202 

So now I'll develop the fix, push a new version on browser stores quickly :smile:

**Comment by RoiArthurB** [comment]
Firefox is updated and I have a little trouble with the Google Store (my addon has been removed, so I have to wait until the addon is back and after I'll be able to upload the update).

Anyway, thanks for your issue! It's fixed now :wink:
