### ISSUE TITLE
How to install it on Chrome?

### ISSUE THREAD

**Issue by fredericky123** [RoiArthurB/Side-Auto_Sci-Hub#20]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Clef-0** [comment]
1. Download and extract the zip from https://github.com/RoiArthurB/Side-Auto_Sci-Hub/releases
2. Delete _config.yml from the folder (Chrome doesn't like reading files starting with _ for some reason but I believe it's only for https://roiarthurb.github.io/Side-Auto_Sci-Hub/ so it's not an issue)
3. Go to Chrome's extensions page, enable Developer Mode
4. Click Load unpacked, and select the extracted zip folder.

you'll also need to right click the Open in Sci Hub toolbar icon now, click Options, then change the URL to https://sci-hub.tw/ or another mirror because whereisscihub.now.sh is down.

**Comment by fredericky123** [comment]
Thanks!

**Comment by RoiArthurB** [comment]
@Clef-0 Can you do a PR to add it all (or can I copy-paste your post) on the README for everyone please ? :D

**Comment by Clef-0** [comment]
Submitted PR :)

As an aside, for Firefox users, it looks like [you can submit addons to AMO to be signed without listing them on AMO](https://wiki.mozilla.org/Add-ons/Extension_Signing#FAQ) (see 'How do I get my add-ons signed if they are not hosted on addons.mozilla.org (AMO)?'), which would let you auto-update the addon outside of AMO and let users install it non-temporarily, and it appears to be an automated review process that they claim won't be used for copyright enforcement. I don't use AMO, so I don't know the details, but their instructions sound pretty straight forward and it would be make the addon convenient for Firefox users again.

**Comment by RoiArthurB** [comment]
I'll take a look at this, thanks a lot for the PR, I close the issue now that it's solved ;)
