### ISSUE TITLE
[DISCUSSION] Page Action v Browser Action

### ISSUE THREAD

**Issue by RoiArthurB** [RoiArthurB/Side-Auto_Sci-Hub#7]
@Jackymancs4 I'm wondering about the choice of Page Action v Browser Action... 🤔  🤔 

I mean, it looks absurd to have the plugin as a page action if it apply on every page.. It turns to be a Browser action finally, or in my sense it does 🤔 

I wanted to have your point of view on that, what do you think?

**Comment by Jackymancs4** [comment]
Quoting from: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Page_actions

> Use a page action when the action is related to the current page, and a browser action when the action is related to the browser as a whole or too many pages.

The way I see it is that it doesn't matter on how many pages it does apply, but the fact that the action modify every time only the specific page you are visiting.

> if it apply on every page

It doesn't have to be this way. You could as an example filter out https://whereisscihub.now.sh/ since it does not make sense to allow the extension on that page (we know for sure it's not a research paper).
